services:
  automator:
    container_name: automator
    platform: linux/amd64
    build:
      context: .
      dockerfile: apps/automator/Dockerfile
    ports:
      - "3200:3200"
    env_file:
      - apps/automator/.env.docker
    volumes:
      - ./data/profiles:/data/profiles
      - ./data/images:/data/images
      - ./data/db:/data/db
    restart: unless-stopped
    networks:
      - insta-puppeteer

  dashboard:
    container_name: dashboard
    platform: linux/amd64
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/dashboard/.env.docker
    volumes:
      - ./data/images:/data/images:ro
      - ./data/db:/data/db
    depends_on:
      - automator
    restart: unless-stopped
    networks:
      - insta-puppeteer

networks:
  insta-puppeteer:
    driver: bridge
